config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  TYPES = %w[chinese italian japanese french belgian]
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: TYPES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: { only_integer: true }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @average = average_review
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :adress, :phone_number, :category)
  end

  def average_review
    # .sum doesn't work!!!
    # maybe iterate over the array of reviews with .each???
    # @restaurant.reviews.sum(0.0) / @restaurant.reviews.size
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::TYPES %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<h1><%= @restaurant.name %></h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Rate the Restaurant</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant_path(restaurant) %> | <%= restaurant.category %></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Rate the Restaurant</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1>Rate the Restaurant</h1>
<h2><%= @restaurant.name %></h2>
<%# calculating average doesn't work (.sum doesn't work...) %>
<%# <% average = @restaurant.reviews.sum(0.0) / @restaurant.reviews.size %> %>
<p>Rating: <%= @average %></p>
<p>Category: <%= @restaurant.category %></p>
<p><%= @restaurant.address %></p>
<p>Phone: <%= @restaurant.phone_number %></p>
<%= link_to 'Add review', new_restaurant_review_path(@restaurant) %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Delete', restaurant_path(@restaurant),
        method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to 'Back', restaurants_path %>

<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %> <br>
    <strong><%= review.rating %></strong></li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>Rate the Restaurant</h1>
<h2><%= @restaurant.name %></h2>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>